gamma: 0.99
critic_lr: 5e-4
replay_buffer_size: 10000
batch_size: 256
stop_mean_reward: 1
initialization_steps: 1500
hidden_cells: [256]
num_agents: 3
base_dir: /mnt/data/MARL/MAPF
experiment_name: simple_spread_v3_qmix
environment_name: simple_spread_v3
env_type: gymnasium
tau: 0.05
mixer_hidden_size: 64
has_lstm: False
has_attention: False
episodes_total: 50000
number_episodes_per_update: 20
number_updates_per_iter: 10
evaluation_frequency: 20
evaluation_episodes: 10
use_vicuna: False
use_oracle: False
